### ISSUE TITLE
Plugin not functioning

### ISSUE THREAD

**Issue by Starvexx** [adsabs/wp-nasaads-query-importer#2]
Hello, I am trying to use you wordpress plugin to query the NASA/ADS and show the result on my webpage. However it seems the plugin is not working. When I try to enter my ADS API token on the settings page, I get an error, stating that there has been a critical error, and that I should check the admin email inbox for instructions. There I get the following error message:

    Error Details
    =============
    An error of type E_ERROR was caused in line 87 of the file /var/www/html/wp-content/plugins/wp-nasaads-query-importer/settings.php. Error message: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /var/www/html/wp-content/plugins/wp-nasaads-query-importer/settings.php:87
    Stack trace:
    #0 /var/www/html/wp-content/plugins/wp-nasaads-query-importer/settings.php(87): strpos()
    #1 /var/www/html/wp-includes/class-wp-hook.php(309): wp_nasaads_query_importer_validate_token()
    #2 /var/www/html/wp-includes/plugin.php(191): WP_Hook->apply_filters()
    #3 /var/www/html/wp-includes/formatting.php(4988): apply_filters()
    #4 /var/www/html/wp-includes/option.php(424): sanitize_option()
    #5 /var/www/html/wp-admin/options.php(322): update_option()
    #6 {main}
    thrown

I am running Wordpress ver. 6.0.1 using the Astra Theme at version 4.0.2

Hopefully you can help me to resolve this issue.

**Comment by telepibe** [comment]
Hello
I had the same problem and implemented some fixes to make it work. You can view the changes I made in #3 and change your copy of the files or download them from my repo.
Take my fixes with a grain of salt since I'm not a proper programmer.
I hope it helps.

**Comment by Starvexx** [comment]
Hey, thanks for your effort, I will take a look and see if your fixes can also work for me. In the meanwhile I have hacked together a solution myself using python. This can be imported to wordpress as as a plugin. For now it works well enough for me, but I intend to expand it in the future.

**Comment by marblestation** [comment]
PR https://github.com/adsabs/wp-nasaads-query-importer/pull/3 has been merged and might fix the problems reported here
