### ISSUE TITLE
PHP issue with Nasa ADS Query Importer

### ISSUE THREAD

**Issue by PeterJohannsenCMT** [adsabs/wp-nasaads-query-importer#4]
I get the following issue when wordpress tries to run the ADS-shortcode: 

```
Warning: Undefined variable $value in /var/www/wp-content/plugins/wp-nasaads-query-importer/shortcodes.php on line 134
```

I thought it might be an outdated ADS token, however, I can't even change the token; it's as though it's missing a "save" button in the wp-nasaads-...  settings 

Server architecture | Linux 5.4.206-200.el7.x86_64 x86_64
Web server | Apache
PHP version | 8.0.27 (Supports 64bit values)

**Comment by marblestation** [comment]
PR https://github.com/adsabs/wp-nasaads-query-importer/pull/3 has been merged and might fix the problems reported here
